/* AUTO-GENERATED by scripts/compile-governance-contracts.mjs. DO NOT EDIT. */
export const GENERATED_POLICY_CONTRACT = {
  "version": 1,
  "policyVersion": "governance-kernel-v1",
  "routes": {
    "observability": {
      "fullTrace": {
        "path": "/observability/trace/:id",
        "access": {
          "actorRoles": [
            "ADMIN",
            "SYSTEM"
          ],
          "tenantFlag": "ALLOW_TRACE_FULL",
          "killSwitch": "DISABLE_TRACE_FULL",
          "requireDebugHeader": true
        }
      }
    }
  },
  "featureFlags": {
    "protected": [
      "ALLOW_TRACE_FULL",
      "DISABLE_TRACE_FULL",
      "BYPASS_TENANT_ISOLATION"
    ]
  },
  "policyGovernanceTargets": [
    "src/observability/observability.controller.ts",
    "src/modules/tenant-feature-flags/tenant-feature-flag.controller.ts",
    "src/saas/saas-admin.controller.ts",
    "src/saas/saas-billing.controller.ts",
    "src/saas/saas-audit.controller.ts",
    "src/saas/saas-tenant.controller.ts"
  ],
  "backend": {
    "controllerPrefixes": [
      "observability",
      "api/v1/observability",
      "feature-flags",
      "saas/admin",
      "saas/tenant",
      "saas/billing",
      "saas/audit",
      "execution",
      "approvals",
      "payments",
      "ingestion",
      "demo",
      "api/v1/execution",
      "dashboard",
      "analytics",
      "api/v1/analytics",
      "events",
      "api/v1/events",
      "api/v1/system",
      "campaigns",
      "system",
      "survival/jobs",
      "health",
      "live",
      "ready",
      "metrics",
      "webhooks"
    ]
  },
  "bff": {
    "browserApiPrefix": "/api/collectiq/",
    "frontendMetricSinkPath": "/api/collectiq/api/v1/metrics/frontend",
    "allowedBackendExact": [
      "/live",
      "/ready",
      "/health"
    ],
    "allowedBackendPrefixes": [
      "/health/",
      "/dashboard/",
      "/observability/",
      "/api/v1/observability",
      "/api/v1/execution",
      "/api/v1/analytics",
      "/api/v1/system",
      "/api/v1/events",
      "/execution/",
      "/approvals/",
      "/payments/",
      "/ingestion/",
      "/feature-flags",
      "/demo/",
      "/saas/tenant/",
      "/saas/billing/",
      "/saas/audit/",
      "/analytics/",
      "/survival/",
      "/campaigns/",
      "/campaigns"
    ],
    "explicitCollectiqRoutes": [
      "/admin/health",
      "/admin/tenants",
      "/admin/tenants/[tenantId]/enabled",
      "/admin/recovery",
      "/auth/login",
      "/auth/logout",
      "/auth/me",
      "/onboarding/activate",
      "/tenant/context"
    ]
  }
} as const;
