import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { resolve } from "node:path";

const envPath = resolve(process.cwd(), ".env");

function parseEnv(content) {
  const map = new Map();
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const idx = trimmed.indexOf("=");
    if (idx <= 0) continue;
    const key = trimmed.slice(0, idx).trim();
    let value = trimmed.slice(idx + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
    map.set(key, value);
  }
  return map;
}

function base64Key32() {
  return randomBytes(32).toString("base64");
}

function apiKey() {
  return randomBytes(24).toString("base64url");
}

const existing = existsSync(envPath) ? parseEnv(readFileSync(envPath, "utf8")) : new Map();
const get = (k, fallback) => {
  const current = existing.get(k)?.trim();
  return current && current.length > 0 ? current : fallback();
};

const values = {
  NODE_ENV: get("NODE_ENV", () => "development"),
  PORT: get("PORT", () => "3000"),
  NEXT_PUBLIC_APP_URL: get("NEXT_PUBLIC_APP_URL", () => "http://localhost:3001"),
  COLLECTIQ_API_KEYS: get("COLLECTIQ_API_KEYS", apiKey),
  COLLECTIQ_DATA_KEY: get("COLLECTIQ_DATA_KEY", base64Key32),
  COLLECTIQ_PII_KEY: get("COLLECTIQ_PII_KEY", base64Key32),
  COLLECTIQ_REQUIRE_TLS: get("COLLECTIQ_REQUIRE_TLS", () => "false"),
  COLLECTIQ_TRUST_PROXY: get("COLLECTIQ_TRUST_PROXY", () => "true"),
  ALLOW_ENV_FALLBACK: get("ALLOW_ENV_FALLBACK", () => "true"),
};

const file = [
  "# Auto-generated by npm run env:auto",
  "# You can safely edit values after generation.",
  "",
  `NODE_ENV=${values.NODE_ENV}`,
  `PORT=${values.PORT}`,
  `NEXT_PUBLIC_APP_URL=${values.NEXT_PUBLIC_APP_URL}`,
  "",
  "# Required security keys",
  `COLLECTIQ_API_KEYS=${values.COLLECTIQ_API_KEYS}`,
  `COLLECTIQ_DATA_KEY=${values.COLLECTIQ_DATA_KEY}`,
  `COLLECTIQ_PII_KEY=${values.COLLECTIQ_PII_KEY}`,
  "",
  "# Runtime flags",
  `COLLECTIQ_REQUIRE_TLS=${values.COLLECTIQ_REQUIRE_TLS}`,
  `COLLECTIQ_TRUST_PROXY=${values.COLLECTIQ_TRUST_PROXY}`,
  `ALLOW_ENV_FALLBACK=${values.ALLOW_ENV_FALLBACK}`,
  "",
].join("\n");

writeFileSync(envPath, file, "utf8");

console.log(`Wrote ${envPath}`);
console.log("Generated/kept backend env values (COLLECTIQ_* and runtime settings).");
