import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const envPath = resolve(process.cwd(), ".env.local");

function parseEnv(content) {
  const map = new Map();
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const idx = trimmed.indexOf("=");
    if (idx <= 0) continue;
    const key = trimmed.slice(0, idx).trim();
    let value = trimmed.slice(idx + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
    map.set(key, value);
  }
  return map;
}

const existing = existsSync(envPath) ? parseEnv(readFileSync(envPath, "utf8")) : new Map();
const get = (k, fallback) => {
  const current = existing.get(k)?.trim();
  return current && current.length > 0 ? current : fallback;
};

const values = {
  NEXT_PUBLIC_API_URL: get("NEXT_PUBLIC_API_URL", "http://localhost:3000"),
  NEXT_PUBLIC_APP_URL: get("NEXT_PUBLIC_APP_URL", "http://localhost:3001"),
  NEXT_PUBLIC_COLLECTIQ_API_KEY: get("NEXT_PUBLIC_COLLECTIQ_API_KEY", ""),
  NEXT_PUBLIC_COLLECTIQ_MAINTENANCE: get("NEXT_PUBLIC_COLLECTIQ_MAINTENANCE", "0"),
  COLLECTIQ_API_BASE_URL: get("COLLECTIQ_API_BASE_URL", "http://localhost:3000"),
  COLLECTIQ_ADMIN_API_KEY: get("COLLECTIQ_ADMIN_API_KEY", ""),
  COLLECTIQ_ADMIN_USER: get("COLLECTIQ_ADMIN_USER", "admin"),
  COLLECTIQ_ADMIN_PASSWORD: get("COLLECTIQ_ADMIN_PASSWORD", "admin123"),
  COLLECTIQ_OPERATOR_USER: get("COLLECTIQ_OPERATOR_USER", "operator"),
  COLLECTIQ_OPERATOR_PASSWORD: get("COLLECTIQ_OPERATOR_PASSWORD", "operator123"),
};

const file = [
  "# Auto-generated by npm run env:auto",
  "# You can safely edit values after generation.",
  "",
  `NEXT_PUBLIC_API_URL=${values.NEXT_PUBLIC_API_URL}`,
  `NEXT_PUBLIC_APP_URL=${values.NEXT_PUBLIC_APP_URL}`,
  `NEXT_PUBLIC_COLLECTIQ_API_KEY=${values.NEXT_PUBLIC_COLLECTIQ_API_KEY}`,
  `NEXT_PUBLIC_COLLECTIQ_MAINTENANCE=${values.NEXT_PUBLIC_COLLECTIQ_MAINTENANCE}`,
  "",
  `COLLECTIQ_API_BASE_URL=${values.COLLECTIQ_API_BASE_URL}`,
  `COLLECTIQ_ADMIN_API_KEY=${values.COLLECTIQ_ADMIN_API_KEY}`,
  `COLLECTIQ_ADMIN_USER=${values.COLLECTIQ_ADMIN_USER}`,
  `COLLECTIQ_ADMIN_PASSWORD=${values.COLLECTIQ_ADMIN_PASSWORD}`,
  `COLLECTIQ_OPERATOR_USER=${values.COLLECTIQ_OPERATOR_USER}`,
  `COLLECTIQ_OPERATOR_PASSWORD=${values.COLLECTIQ_OPERATOR_PASSWORD}`,
  "",
].join("\n");

writeFileSync(envPath, file, "utf8");
console.log(`Wrote ${envPath}`);
console.log("Generated/kept frontend NEXT_PUBLIC_* and server-side BFF vars.");
